import pandas as pd
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# Load the CSV file
input_csv = BASE_DIR / "Tool_CSV" / "results-survey641369.csv"
df = pd.read_csv(input_csv)

# Define the columns
code_column = 'Please paste here the confirmation code generated by the tool. '
id_column = 'Unnamed: 7'
target_code = '761528'

# Filter the data
filtered_df = df[df[code_column] == target_code]

# Get the IDs
ids = filtered_df[id_column].tolist()

# Print results
print(f"Found {len(ids)} IDs:")
for pid in ids:
    print(pid)

# Persist the filtered IDs so they can be inspected later.
output_dir = BASE_DIR / "outputs"
output_dir.mkdir(parents=True, exist_ok=True)
output_path = output_dir / "filter_limesurvey_ids.csv"
filtered_df[[id_column]].rename(columns={id_column: "prolific_id"}).to_csv(
    output_path, index=False, encoding="utf-8"
)